services:
    nginx-container:
        image: nginx
        container_name: "laravel-nyumon-nginx"
        ports:
            - "${DOCKER_PORT:-8888}:80"
        volumes:
            - ./:/var/www/:cached
            - ./server/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-container

    yarn_installation:
        container_name: laravel-nyumon-yarn-installation
        image: node:22-bookworm
        volumes:
          - ./:/app
        entrypoint:
            - sh
        command:
            # .exec-once-yarnというファイルが存在するというファイルがあったら実行しない
            # 最初にコマンド実行がなされていたら、.exec-once-yarnというファイルが作成されるようにしている
            # .exec-once-yarnがあるが、すでにyarn installなどが実行されているケースもあるため、
            # 注意すること。もし.exec-once-yarnがあるのに、次のものが存在する場合は、何かしら個人で触った影響。
            # 1. node_modulesディレクトリがある
            - -c
            - |
              [ -f ./.exec-once-yarn ] || {
                yarn install && touch ./.exec-once-yarn
              }

    php-container:
        build: ./server/docker/php
        container_name: "laravel-nyumon-php"
        volumes:
            - ./:/var/www:cached
        depends_on:
            - yarn_installation
        env_file:
            - .env

    mysql-container:
        container_name: "laravel-nyumon-mysql"
        build:
          context: ./server/docker/mysql
          dockerfile: Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASS:-dev}
            MYSQL_USER: ${DOCKER_DB_USERNAME:-dev}
            MYSQL_PASSWORD: ${DOCKER_DB_PASSWORD:-dev}
            MYSQL_DATABASE: ${DOCKER_DB_DATABASE:-laravel_nyumon}
            MYSQL_TCP_PORT: ${DOCKER_DB_PORT:-53306}
        ports:
            - "${DOCKER_DB_PORT:-53306}:${DOCKER_DB_PORT:-53306}"
        volumes:
            - ./server/docker/mysql/init:/docker-entrypoint-initdb.d
            - laravel-nyumon-mysql-data:/var/lib/mysql:cached

    adminer:
        image: adminer
        restart: always
        ports:
          - 58080:8080
        environment:
            ADMINER_DEFAULT_SERVER: mysql-container
            ADMINER_DESIGN: galkaev

volumes:
    laravel-nyumon-mysql-data:
        driver: local